name: pythermondt-dev
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  # General
  - python=3.12.*
  - pytest=8.3.*
  - pylint=3.2.*
  - progressbar2=4.5.*

  # Data loading and visualization
  - mat73=0.65
  - numpy=1.26.*
  - matplotlib=3.9.*

  # Machine Learning
  - pytorch=2.3.*
  - cpuonly
  
  # AWS upload
  - boto3=1.35.*
  - sagemaker-python-sdk=2.227.*
