name: pythermondt-dev
channels:
  - defaults
dependencies:
  # General
  - python=3.12.*
  - pip
  - pip:
    - "-e ." # Install the package in editable mode
    - "-r requirements_dev.txt" # Install all dependencies from requirements_dev.txt
