[project]
name = "pythermondt"
dynamic = ["version"]
description = "A Python package for manipulating thermographic data in Non-Destructive Testing (NDT) applications."
authors = [{name = "Julian Grimm", email = "julian.grimm@fh-wels.at"}]
license = {file = "LICENSE"}
readme = "README.md"

[tool.setuptools.packages.find]
where = ["./src"]

[tool.setuptools.dynamic]
version = {attr = "pythermondt._version.__version__"}

[tool.pytest.ini_options]
addopts = "-vv"
testpaths = [
    "./tests",
]
pythonpath = [
    "./src",
]