[build-system]
requires = ["setuptools>=66.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pythermondt"
dynamic = ["version"]
description = "A Python package for manipulating thermographic data in Non-Destructive Testing (NDT) applications."
authors = [{name = "Julian Grimm", email = "julian.grimm@fh-wels.at"}]
license = {file = "LICENSE"}
readme = "README.md"
requires-python = ">=3.10, <3.13"
dependencies = [
    # General dependencies
    "tqdm>=4.65",
    "ipywidgets>=8.0",
    "ipykernel>=6.25",

    # Data loading and visualization
    "h5py>=3.9",
    "mat73>=0.65",
    "numpy>=1.23",
    "matplotlib>=3.7",

    # Machine learning
    "torch>=2.0",

    # AWS
    "boto3>=1.33",
]

[project.optional-dependencies]
dev = [
    "pytest>=8.3",
    "pytest-cov>=4.1",
    "uv>=0.4",
    "ruff>=0.6",
    "pre-commit>=3.8"
]

[tool.setuptools.packages.find]
where = ["./src"]

[tool.setuptools.dynamic]
version = {attr = "pythermondt.__pkginfo__.__version__"}

[tool.pytest.ini_options]
addopts = [
    "-vv",
    "--import-mode=importlib",
]
testpaths = ["tests"]

[tool.uv]
required-version = "~=0.6.0" # Pin uv to major version 0.6 for stability