[project]
name = "pythermondt"
version = "0.0.2"
description = "A Python package for manipulating thermographic data in Non-Destructive Testing (NDT) applications."
authors = [{name = "Julian Grimm", email = "julian.grimm@fh-wels.at"}]
license = {file = "LICENSE"}
readme = "README.md"

[tool.setuptools.packages.find]
where = ["./src"]

[tool.pytest.ini_options]
addopts = "-vv"
testpaths = [
    "./tests",
]
pythonpath = [
    "./src",
]