name: Build and Release Python Package

on:
  workflow_dispatch:

jobs:
  # Job 1: Validate and prepare the release branch. Also check if an official release already exists
  prepare:
    runs-on: ubuntu-latest
    outputs:
      release_version: ${{ steps.bump.outputs.current-version }}
      release_exists: ${{ steps.check_release.outputs.RELEASE_DOES_EXIST }}
      is_draft: ${{ steps.check_release.outputs.IS_DRAFT }}
      is_published: ${{ steps.check_release.outputs.IS_PUBLISHED }}
    steps:
      # Step 1: Checkout code in the current branch
      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for tags history

      # Step 2: Setup uv
      - name: Setup uv
        id: setup-uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: '3.12'
          enable-cache: false

      # Step 3: Install bump-my-version
      - name: Install bump-my-version
        run: |
          uv pip install bump-my-version==1.0.2

      # Step 4: Get current version
      - name: Get current version
        id: get_current_version
        run : |
          echo "current-version=$(bump-my-version show current_version)" >> $GITHUB_OUTPUT

      # Step 5: Bump the version
      - name: Bump to release version
        id: bump
        run: |
          echo "previous-version=$(bump-my-version show current_version)" >> $GITHUB_OUTPUT
          bump-my-version bump release
          ([[ $? -gt 0 ]] && echo "bumped=false" || echo "bumped=true") >> $GITHUB_OUTPUT
          echo "current-version=$(bump-my-version show current_version)" >> $GITHUB_OUTPUT

      # Step 6: Check if an official release already exists
      - name: Check if release exists
        id: check_release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Get release info and debug output
          RELEASE_INFO=$(gh release view ${{ steps.bump.outputs.current-version }} --json isDraft,isPrerelease,publishedAt --jq '[.isDraft, .isPrerelease, .publishedAt]' 2>&1 || echo "not_found")
          echo "Debug - Release Info: $RELEASE_INFO"

          if [[ "$RELEASE_INFO" == *"not_found"* ]]; then
            echo "RELEASE_DOES_EXIST=false" >> $GITHUB_OUTPUT
          else
            echo "RELEASE_DOES_EXIST=true" >> $GITHUB_OUTPUT

            # Parse the JSON array properly
            IS_DRAFT=$(echo $RELEASE_INFO | jq -r '.[0]')
            IS_PRERELEASE=$(echo $RELEASE_INFO | jq -r '.[1]')
            PUBLISHED_AT=$(echo $RELEASE_INFO | jq -r '.[2]')

            if [[ "$IS_DRAFT" == "false" && "$PUBLISHED_AT" != "null" ]]; then
              echo "IS_PUBLISHED=true" >> $GITHUB_OUTPUT
            else
              echo "IS_PUBLISHED=false" >> $GITHUB_OUTPUT
            fi

            echo "IS_DRAFT=$IS_DRAFT" >> $GITHUB_OUTPUT
          fi

      # Step 7: Stop workflow if an official release already exists
      - name: Stop if official release exists
        if: steps.check_release.outputs.IS_PUBLISHED == 'true'
        run: |
          echo "An official release with the tag ${{ steps.bump.outputs.current-version }} already exists. Stopping workflow."
          exit 1

  # Job 2: Run test using pytest
  test:
    uses: ./.github/workflows/tests.yml

  # Job 3: Lint the source code
  lint:
    uses: ./.github/workflows/lint.yml

  # Job 4: Build the package (conda or pip) and upload artifacts using a matrix job
  build:
    needs: prepare
    if: needs.prepare.outputs.release_exists == 'false' || needs.prepare.outputs.is_draft == 'true'
    uses: ./.github/workflows/build.yml
    with:
      release_version: ${{ needs.prepare.outputs.release_version }}

  # Job 5: Release the package
  release:
    needs: [prepare, build, test, lint]
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code in the current branch
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Setup uv
      - name: Setup uv
        id: setup-uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: '3.12'
          enable-cache: false

      # Step 3: Install bump-my-version
      - name: Install bump-my-version
        run: |
          uv pip install bump-my-version==1.0.2

      # Step 4: Setup github user
      - name: Setup git user
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      # Step 5: Delete existing release branch if it exists and release is draft. Rejected if release is published
      - name:
        run: |
          if [[ "${{ needs.prepare.outputs.release_exists }}" == "true" && "${{ needs.prepare.outputs.is_draft }}" == "true" ]]; then
            git branch -D release/${{ needs.prepare.outputs.release_version }}
            git push origin --delete release/${{ needs.prepare.outputs.release_version }}
          elif [[ "${{ needs.prepare.outputs.release_exists }}" == "true" && "${{ needs.prepare.outputs.is_draft }}" == "false" ]]; then
            echo "An official release with the tag ${{ needs.prepare.outputs.release_version }} already exists. Stopping workflow."
            exit 1
          fi

      # Step 6: Create a release branch from the current branch and delete exsting if release is draft
      - name: Create release branch
        run: |
          git branch -m release/${{ needs.prepare.outputs.release_version }}
          git push origin release/${{ needs.prepare.outputs.release_version }}

      # Step 7: Bump the version
      - name: Bump to release version
        id: bump
        run: |
          echo "previous-version=$(bump-my-version show current_version)" >> $GITHUB_OUTPUT
          bump-my-version bump release --commit
          ([[ $? -gt 0 ]] && echo "bumped=false" || echo "bumped=true") >> $GITHUB_OUTPUT
          echo "current-version=$(bump-my-version show current_version)" >> $GITHUB_OUTPUT

      # Step 8: Delete existing draft release if it exists
      - name: Delete existing draft release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: needs.prepare.outputs.release_exists == 'true' && needs.prepare.outputs.is_draft == 'true'
        run: |
          gh release delete ${{ needs.prepare.outputs.release_version }} --yes

      # Step 9: Download artifacts from previous job
      - name: Download artifacts from build job
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      # Step 10: Create new draft release with all packages
      - name: Create Draft Release
        if: needs.prepare.outputs.release_exists == 'false' || needs.prepare.outputs.is_draft == 'true'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.prepare.outputs.release_version }}
          name: pyThermoNDT ${{ needs.prepare.outputs.release_version }}
          body: |
            ## Release Contents
            - Conda Package (.zip): Full conda package with all dependencies (for conda installation)
            - Wheel Package (.whl): Python wheel distribution (recommended for pip installation)
            - Source Package (.tar.gz): Source distribution
          files: |
            artifacts/**/*
          generate_release_notes: true
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
