name: Bump version
description: 'Reusable workflow to bump the version of PyThermoNDT'

on:
  workflow_call:
    inputs:
      bump-type:
        description: 'The type of bump to perform'
        required: true
        type: string
        default: 'patch'
      ref:
        description: 'The branch or tag to bump the version in'
        required: true
        type: string
        default: ''
    secrets:
      WRITE_KEY:
        description: 'SSH key to push changes'
        required: true
    outputs:
      bumped:
        description: 'Whether the version was bumped'
        value: ${{ jobs.bump.outputs.bumped }}
      previous-version:
        description: 'The previous version'
        value: ${{ jobs.bump.outputs.previous-version }}
      current-version:
        description: 'The current version'
        value: ${{ jobs.bump.outputs.current-version }}

  workflow_dispatch:
    inputs:
      bump-type:
        description: 'The type of bump to perform'
        required: true
        default: 'patch'
        type: choice
        options:
        - major
        - minor
        - patch
        - release


jobs:
  bump:
    runs-on: ubuntu-latest
    outputs:
      bumped: ${{ steps.bump.outputs.bumped }}
      previous-version: ${{ steps.bump.outputs.previous-version }}
      current-version: ${{ steps.bump.outputs.current-version }}
    steps:
      # Step 1.1: Checkout repository (workflow_call) (see https://dev.to/koseimori/conditional-branching-with-workflowdispatch-and-workflowcall-in-github-actions-oik)
      - name: Checkout repository
        if: github.event.workflow != '.github/workflows/bump_version.yml'
        uses: actions/checkout@v5.0.0
        with:
          fetch-depth: 0  # Required for tags history
          ssh-key: ${{ secrets.WRITE_KEY }} # TODO: Replace with GitHub App: https://github.com/orgs/community/discussions/25305#discussioncomment-8256560
          ref: ${{ inputs.ref }}

      # Step 1.2: Checkout repository (workflow_dispatch)
      - name: Checkout repository
        if: github.event.workflow == '.github/workflows/bump_version.yml'
        uses: actions/checkout@v5.0.0
        with:
          fetch-depth: 0  # Required for tags history
          ssh-key: ${{ secrets.WRITE_KEY }} # TODO: Replace with GitHub App: https://github.com/orgs/community/discussions/25305#discussioncomment-8256560

      # Step 2: Setup uv
      - name: Setup uv
        id: setup-uv
        uses: astral-sh/setup-uv@v6.5.0
        with:
          version-file: requirements_dev.txt
          python-version: ${{ vars.DEFAULT_PYTHON_VERSION }}
          activate-environment: true
          enable-cache: false

      # Step 3: Install bump-my-version
      - name: Install bump-my-version
        run: |
          uv pip install bump-my-version --overrides ./requirements_dev.txt

      # Step 4: Setup github user
      - name: Setup git user
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      # Step 5: Bump version
      - name: Bump version
        id: bump
        run: |
          echo "previous-version=$(bump-my-version show current_version)" >> $GITHUB_OUTPUT
          bump-my-version bump ${{ inputs.bump-type }} --commit
          ([[ $? -gt 0 ]] && echo "bumped=false" || echo "bumped=true") >> $GITHUB_OUTPUT
          echo "current-version=$(bump-my-version show current_version)" >> $GITHUB_OUTPUT

      # Step 6: Check if the version was bumped
      - name: Check
        if: steps.bump.outputs.bumped == 'true'
        run: |
          echo "Version was bumped from ${{ steps.bump.outputs.previous-version }} to ${{ steps.bump.outputs.current-version }}!"

      # Step 7: Push changes
      - name: Push changes
        if: steps.bump.outputs.bumped == 'true'
        run: |
          git push
          git push --tags
