name: Run Linters
description: 'Reuseable workflow to run linting for pyThermoNDT'

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      ref:
        description: 'The branch or tag to lint. Defaults to the reference of the workflow trigger'
        type: string
        default: ''

jobs:
  lint:
    name: Run Ruff
    runs-on: ubuntu-latest
    steps:
      # Step 1.1: Checkout repository (workflow_call)
      - name: Checkout repository
        if: github.event_name == 'workflow_call'
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      # Step 1.2: Checkout repository (workflow_dispatch)
      - name: Checkout repository
        if: github.event_name == 'workflow_dispatch'
        uses: actions/checkout@v4

      # Step 2: Setup ruff
      - name: Setup and run ruff
        uses: astral-sh/ruff-action@v3
        with:
          args: "check"

      # Step 3: Set Output Based on Lint Success
      - id: set_output
        if: success()
        run: echo "success=true" >> $GITHUB_OUTPUT
