name: Run Tests
description: 'Reusable workflow to run all tests for PyThermoNDT'

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      ref:
        description: 'The branch or tag to test. Defaults to the reference of the workflow trigger'
        type: string
        default: ''

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
    steps:
      # Step 1.1: Checkout repository (workflow_call) (see https://dev.to/koseimori/conditional-branching-with-workflowdispatch-and-workflowcall-in-github-actions-oik)
      - name: Checkout repository
        if: github.event.workflow != '.github/workflows/tests.yml'
        uses: actions/checkout@v6.0.1
        with:
          ref: ${{ inputs.ref }}

      # Step 1.2: Checkout repository (workflow_dispatch)
      - name: Checkout repository
        if: github.event.workflow == '.github/workflows/tests.yml'
        uses: actions/checkout@v6.0.1

      # Step 2: Setup uv
      - name: Setup uv
        id: setup-uv
        uses: astral-sh/setup-uv@v7.2.0
        with:
          version-file: requirements_dev.txt
          python-version: ${{ matrix.python-version }}
          activate-environment: true
          cache-dependency-glob: ${{ vars.CACHE_DEPENDENCY_GLOB }}
          save-cache: false

      # Step 3 Sync dependencies if cache hit
      - name: Sync dependencies
        run: |
          uv pip install -r ./requirements_dev.txt # Install dev dependencies
          uv pip install . --torch-backend cpu # Set the backend to CPU to avoid installing cuda dependencies

      # Step 4: Run tests without coverage
      - name: Run Tests
        if: matrix.python-version != vars.DEFAULT_PYTHON_VERSION
        run: pytest --benchmark-skip

      # Step 4.1: Run tests with coverage on default python version
      - name: Run Tests
        if: matrix.python-version == vars.DEFAULT_PYTHON_VERSION
        run: pytest --junitxml=pytest.xml --cov-report=term-missing:skip-covered --cov=pythermondt --ignore=tests/benchmark tests/ | tee pytest-coverage.txt

      # Step 5: Create artifact for coverage data
      - name: Upload coverage data
        if: matrix.python-version == vars.DEFAULT_PYTHON_VERSION
        uses: actions/upload-artifact@v6.0.0
        with:
          name: coverage-data-python-${{ matrix.python-version }}
          path: |
            coverage.xml
            pytest.xml
            pytest-coverage.txt
