name: Run Tests
description: 'Reusable workflow to run all tests for pyThermoNDT'

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      ref:
        description: 'The branch or tag to test. Defaults to the reference of the workflow trigger'
        type: string
        default: ''

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    steps:
      # Step 1.1: Checkout repository (workflow_call) (see https://dev.to/koseimori/conditional-branching-with-workflowdispatch-and-workflowcall-in-github-actions-oik)
      - name: Checkout repository
        if: github.event.workflow != '.github/workflows/tests.yml'
        uses: actions/checkout@v4.2.2
        with:
          ref: ${{ inputs.ref }}

      # Step 1.2: Checkout repository (workflow_dispatch)
      - name: Checkout repository
        if: github.event.workflow == '.github/workflows/tests.yml'
        uses: actions/checkout@v4.2.2

      # Step 2: Setup uv
      - name: Setup uv
        id: setup-uv
        uses: astral-sh/setup-uv@v6.1.0
        with:
          python-version: ${{ matrix.python-version }}
          activate-environment: true
          cache-dependency-glob: ${{ vars.CACHE_DEPENDENCY_GLOB }}

      # Step 3 Sync dependencies if cache hit
      - name: Sync dependencies
        run: |
          uv pip install -r ./requirements_dev.txt # Install dev dependencies
          uv pip install . --torch-backend cpu # Set the backend to CPU to avoid installing cuda dependencies

      # Step 4: Run tests
      - name: Run Tests
        run: pytest
