# Updates the cache in main branch, because only caches from default branch are available in other branches. ==> allows for faster CI in other branches
name: update-cache

on:
  workflow_dispatch:
  push:
    branches:
      - "main" # Update cache on main branch

jobs:
  build-cache:
    name: Build Cache
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v5.0.0

      # Step 2: Setup uv
      - name: Setup uv
        id: setup-uv
        uses: astral-sh/setup-uv@v6.8.0
        with:
          version-file: requirements_dev.txt
          python-version: ${{ matrix.python-version }}
          activate-environment: true
          cache-dependency-glob: ${{ vars.CACHE_DEPENDENCY_GLOB }}

      # Step 3 Sync dependencies if cache hit
      - if: steps.setup-uv.outputs.cache-hit != 'true'
        name: Sync dependencies
        run: |
          uv pip install -r ./requirements_dev.txt # Install dev dependencies
          uv pip install . --torch-backend cpu # Set the backend to CPU to avoid installing cuda dependencies
