# Updates the cache in main branch, because only caches from default branch are available in other branches. ==> allows for faster CI in other branches
name: update-cache

on:
  workflow_dispatch:
  push:
    branches:
      - "main" # Update cache on main branch

# Environment variables
env:
  UV_SYSTEM_PYTHON: 1 # Use system python
  UV_CACHE_DIR: /tmp/.uv-cache # Configure a constant location for the uv cache

jobs:
  build-cache:
    name: Build Cache
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Setup uv
      - name: Install uv and setup python environment
        id: setup-uv
        uses: astral-sh/setup-uv@v5
        with:
          # Install a specific version of uv.
          version: "0.5.31" # Pin uv version for stability
          enable-cache: true
          cache-dependency-glob: |
            **/pyproject.toml
            **/setup.py

      # Step 3: Install dependencies if cache miss
      - if: steps.setup-uv.outputs.cache-hit != 'true'
        name: Install dependencies
        run: |
          uv pip install ".[dev]"
